name: vscode_for_android
description: VS Code for Android
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.4.0
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  signale: ^0.0.9
  flutter_spinkit: ^5.2.0
  intl: ^0.19.0
  url_launcher: ^6.1.10
  retrofit: ^4.4.1
  archive: ^3.1.2
  dio: ^5.7.0
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_markdown: ^0.6.10+2
  xterm:
    git:
      url: https://github.com/TerminalStudio/xterm.dart
      ref: master
  settings:
    git: https://github.com/nightmare-space/settings
  flutter_pty:
    git: https://github.com/TerminalStudio/flutter_pty
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  path: ^1.8.0
  device_info_plus: ^11.1.1
  meta: ^1.11.0
  typed_data: ^1.3.2
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

dependency_overrides:
  permission_handler: ^10.2.0
#  global_repository:
#    path: ./global_repository
#
#  settings:
#    path: ./settings
